server:
  port: 808
  servlet:
    session:
      timeout: 60000
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mine
    username: root
    password: rootpwd
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: song-group
      auto-offset-reset: latest